### ISSUE TITLE
next_slide event emitting only on manual click/swipe to next slide

### ISSUE THREAD

**Issue by ribagek** [maxal-studio/vue3-insta-stories#1]
Hello!

next_slide event emitting only on manual click/swipe to next slide. But it's not emitting when slide is changed naturally when slide's duration time is over.

Please help and thanks!

**Comment by dajanvulaj** [comment]
Hello @ribagek,

Thanks for the feedback.

I've pushed a new update online.

`@prev_slide` and `@next_slide` events will emit only on slide change, not story change.
If you want to catch every slide change, including story change, use `@slide_changed`

Thanks,
Dajan

**Comment by vdomah** [comment]
thanks for super fast fix! It's me @ribagek
